### ISSUE TITLE
In order to debug this project, add an executable project to this solution

### ISSUE THREAD

**Issue by vince-lynch** [zac7f/Socks5#30]
Hi, I'm trying to debug the socks5 (as my startup project).

I'm getting the error,
A project with an output type of class cannot be started directly. 
In order to debug this project, add an executable project to this solution.

Whenever I do a build no executable (.exe) file is generated.

Please advise?
Thankyou
Vince

**Comment by zac7f** [comment]
You'll need to add a reference to the socks5 project in order to debug it... This is a library, not a console application.
